### PR TITLE
Create cert-chains and move appropriate things.

### LINKED ISSUE #124: Move `.pem` files from certs/ to certs/cert-chains
Right now, they show up in the same folder as some other stuff that makes everything really confusing:

- `.gitignore`
- `cert-generator`
- `foreign`
- `self-signed`

### PR DESCRIPTION
**Pull request by Hoverbear**
Destined to close #124.

### CODE REVIEW

**Comment by lgarron** [comment]
> ??

I actually meant to move all certificate chains here, so that I can avoid this mess:

screen shot 2015-12-15 at 19 38 19

(Preferably only the chains; the other stuff can live in e.g. self-signed..)

**Comment by Hoverbear** [comment]
Hmm just the `.pem` files? I moved the `.pem` and `.key`s.

**Comment by lgarron** [comment]
Yeah, the keys are not part of the cert chains. ;-)

(Also, I think this CL missed some of the pems?)

**Comment by Hoverbear** [comment]
Okay, do you think we should put the `.key`s somewhere else as a group, or in the same old folder structure?

**Comment by Hoverbear** [comment]
@lgarron Ping. :)

**Comment by lgarron** [comment]
> Okay, do you think we should put the .keys somewhere else as a group, or in the same old folder structure?

Anywhere sensible, really. I'd probably just create a "certs/keys" folder.

**Comment by Hoverbear** [comment]
Should be good to go! Apologies for the mess of my last PR on this, I use the `make docker` command and don't see much of the final FS. @marumari 's PR #134 fixes some remaining quirks.

**Comment by Hoverbear** [comment]
I've rebased this. :) Please merge with care as I'm not sure how it will handle your non-self signed keys.

**Comment by Hoverbear** [comment]
Ping @lgarron. :)

**Comment by Hoverbear** [comment]
Ping @lgarron :) Is there anything I can do to help merge this?

**Comment by lgarron** [comment]
> Is there anything I can do to help merge this?

One thing that makes me put these reviews off is that Prod Still Doesn't Resemble Dev. I know, silly excuse, but I need to put time into making it frictionless to test and deploy these changes. If you have quick ideas to make that happen, you could convince me I should just go and do it. :-P

**Comment by Hoverbear** [comment]
I totally understand. :)

Can you give us a better idea of what prod looks like? I know I mostly test via the `make docker` command.

**Comment by lgarron** [comment]
Obsoleted by b02f505f02c31c937f9e69751956bd647ebdb941. I hope you'll forgive me. ;-)

**Pull request closed without merging**
