### PR TITLE
Ordering

### LINKED ISSUE #166: Docker setup doesn't work; `make install` should be after `make jekyll`?
Docker setup doesn't work out of the box:
```bash
$ make docker
sudo docker build -t badssl .
...
Sending build context to Docker daemon 7.457 MB
Step 1 : FROM ubuntu:16.04
 ---> 17b6a9e179d7
Step 2 : MAINTAINER April King <april@twoevils.org>
 ---> Using cache
 ---> 496c4e159766
Step 3 : EXPOSE 80 443
 ---> Using cache
 ---> 43f7090ccd2a
Step 4 : RUN apt-get update && apt-get install -y     build-essential     git     make     nginx     ruby     ruby-dev
 ---> Using cache
 ---> 9bbe69580e2d
Step 5 : RUN gem install jekyll
 ---> Using cache
 ---> b24fb3692d8b
Step 6 : ADD . badssl.com
 ---> 79911ecdaab9
Removing intermediate container c7935c0d8c5f
Step 7 : WORKDIR badssl.com
 ---> Running in 5cb3d08bd206
 ---> 7dd27573c74c
Removing intermediate container 5cb3d08bd206
Step 8 : RUN make install
 ---> Running in 1fd64c9b4899
./_site/certs/cert-generator/cert-generator.sh y
make: ./_site/certs/cert-generator/cert-generator.sh: Command not found
make: *** [keys] Error 127
```

It works if I change the Dockerfile to run `make jekyll` after `make install`, but not sure if that's the right fix or not. @Hoverbear

### PR DESCRIPTION
**Pull request by Hoverbear**
This fixes #166 and is related to #165. Some of these changes are also part of #156.

@estark37 can you please review and test that this fixes the issues? Then we can merge!

### CODE REVIEW

**Comment by lgarron** [comment]
Thanks for making this; it captures the things I remember having to work around last I tried to set up a server from scratch; I'll run a test on our second Google Cloud server right now.

**Comment by lgarron** [comment]
This seems to be working at 104.197.232.8

I'll test it a bit more and then merge.

We also need to expose more ports in the future; I'll make a new issue for that.

**Comment by lgarron** [comment]
@marumari, sound good to merge this?

**Comment by marumari** [comment]
Yep, I got my words in edgewise.  :)

On May 10, 2016, at 2:15 PM, Lucas Garron <notifications@github.com> wrote:

@marumari <https://github.com/marumari>, sound good to merge this?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/google/badssl.com/pull/167#issuecomment-218260803>

**Pull request merged**
